---
- name: 'Run profile task'
  import_tasks: profile.yaml

- name: 'Install some basics'
  apt:
    pkg:
      - vim
      - netdata
      - python3-pip
    update_cache: yes

- name: 'Update root certificates'
  apt:
    pkg:
      - ca-certificates
  notify: Rebuild Root CA Bundle

- name: 'Set netdata configuration'
  copy:
    src: netdata.conf
    dest: /etc/netdata/netdata.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart netdata
