---
# This role based loosely on https://metis.fi/en/2018/02/unifi-on-gcp/

- name: Install Nginx to serve Let's Encrypt challenge files
  import_tasks: install-nginx.yaml

# Obtain/renew LetsEncrypt certificate
- name: Run LetsEncrypt
  import_tasks: letsencrypt.yaml

- name: Recommended dependencies
  apt:
    pkg:
      - ca-certificates
      - apt-transport-https
      - openjdk-17-jdk
    state: latest
    update_cache: no

- name: Add MongoDB 7.0 GPG key
  apt_key:
    url: https://pgp.mongodb.com/server-7.0.asc
    state: present

- name: Add MongoDB 7.0 Repo
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main
    state: present
    filename: mongodb-org-7.0
    update_cache: yes

- name: Install MongoDB 7.0
  apt:
    name: mongodb-org
    state: present

- name: Freeze Mongo Versions
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - mongodb-org
    - mongodb-org-database
    - mongodb-org-server
    - mongodb-mongosh
    - mongodb-org-mongos
    - mongodb-org-tools

- name: Add the Ubiquiti Apt GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 06E85760C0A52C50

- name: Add the Ubiquiti Apt Repo
  apt_repository:
    repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
    state: present
    filename: 100-ubnt-unifi

- name: Install Unifi Software
  apt:
    name: unifi
    state: present

- name: Install DB Repair Service
  import_tasks: install-repair-service.yaml

- name: Install Backup Service
  import_tasks: install-backup-service.yaml

- name: Install Certificate
  import_tasks: install-certificate.yaml
